### PR TITLE
Fixes #1 npm unmarshalling

### LINKED ISSUE #1: json: cannot unmarshal bool into Go struct field error
Hi there

Thanks for a great tool!

 We have checked a large number of package.json files. Sometimes the tool fails with this message:
Encountered an error while trying to read packages from file: json: cannot unmarshal bool into Go struct field PackageJSON.bundleDependencies of type []string

For instance when running against this file npm\node_modules\decamelize\package.json

I don't know if it's a general bug or something at our end.

Thanks!

### PR DESCRIPTION
**Pull request by n0ncetonic**
Fixes #1 by adding `omitempty` tags to the `PackageJSON` struct as not all `package.json` files contain every field in this struct.

Also satisfies `golint` by adding `godoc` comments to exported types, methods, and interfaces, as well as adding package level documentation.

Finally, simplifies the `range` statements in `npm.go` by removing the unnessary `_` empty variable

### CODE REVIEW

**Comment by n0ncetonic** [comment]
Hang tight on merging this as the original issue appears to be unresolved on the issue creator's side. Known working and non working packages have been provided for testing against and once i get some rest I'll fix my pull request

**Comment by joohoi** [comment]
I think it would be reasonable to not to break on error returned from json marshaller at https://github.com/visma-prodsec/confused/blob/main/npm.go#L35-L38

I think it would be fine to just output a warning text with the error instead.

**Review by joohoi — CHANGES_REQUESTED** [review]
I reviewed this PR, and I really much appreciate the added comments in addtion to the functional changes. Thanks!

When we can agree on solution regarding handling the json unmarshaller errors, this is good to get merged.

**Comment by joohoi** [comment]
As a part of adding automated go linter checks to the repository, I fixed some of the linter issues that were also fixed by you in context of this PR, which caused the merge conflict. Sorry for that!

**Comment by joohoi** [comment]
Closing this in favor of #11 

I based the #11 on your branch @n0ncetonic to preserve authorship of the existing changes.

**Comment by n0ncetonic** [comment]
Thanks for that @joohoi . Work got busy so I wasn't able to triage this. Glad you got ahead of it

**Pull request closed without merging**
